---
apiVersion: v1
kind: Service
metadata:
  name: ai-stack-shane-headless
spec:
  clusterIP: None
  selector:
    app: ai-stack-shane
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: jupyter
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: code-server
      port: 7777
      targetPort: 7777
      protocol: TCP
    - name: frontend
      port: 3002
      targetPort: 3002
      protocol: TCP
    - name: backend
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ai-stack-shane
spec:
  serviceName: ai-stack-shane-headless
  replicas: 1
  selector:
    matchLabels:
      app: ai-stack-shane
  template:
    metadata:
      labels:
        app: ai-stack-shane
    spec:
      runtimeClassName: nvidia
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dtc-w1
                      - dtc-w2
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - dtc-w1
      containers:
        - name: ai-stack-shane
          image: 172.128.0.11:30500/dtc/ai-stack:gpu-cu128-tf2.18-torch2.7-jproot-coder-2026.05.12.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
              name: jupyter
            - containerPort: 22
              name: ssh
            - containerPort: 8889
              name: ssh-info
          env:
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ai-shane-code-server
                  key: password
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-ai-shane-code-server
                  key: password
            - name: JUPYTER_PORT
              value: "8888"
            - name: CODE_SERVER_PORT
              value: "7777"
            - name: CODE_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ai-shane-code-server
                  key: password
          resources:
            limits:
              nvidia.com/gpu.shared: 1
              cpu: "8"
              memory: 128Gi
            requests:
              nvidia.com/gpu.shared: 1
              cpu: "8"
              memory: 128Gi
          volumeMounts:
            - name: app-storage
              mountPath: /data
            - name: dshm
              mountPath: /dev/shm

      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: ai-shane-network-pvc-rwx
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ai-stack-shane-nodeport
spec:
  type: NodePort
  selector:
    app: ai-stack-shane
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
      nodePort: 30783
    - name: jupyter
      port: 8888
      targetPort: 8888
      protocol: TCP
      nodePort: 30784
    - name: code-server
      port: 7777
      targetPort: 7777
      protocol: TCP
      nodePort: 30785
    - name: frontend
      port: 3002
      targetPort: 3002
      protocol: TCP
      nodePort: 30786
    - name: backend
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30787