"""Kernel v1 acceptance: parameter calibration via simulated series.

Case map (technical track, roadmap §1.2 calibration path):
- closed-loop consistency -> series generated by floor λ; fit recovers it with ~0 residual
- tagged series           -> decay/delta separation; delta steps carry no signal
- fallback keeps floor    -> unusable series (huge residual) => floor kept, residual recorded
- real-series interface   -> same fit path accepts externally supplied tagged measurements
- determinism             -> same seeds => same report
"""

from __future__ import annotations

import pytest

from lifeos.kernel.calibrate import (
    DECAY_TAG,
    DELTA_TAG,
    calibrate_params,
    fit_lambda,
    simulate_decay_series,
)
from lifeos.kernel.decay import DECAY_PARAMS, KERNEL_STATES, decay_value

SEEDS = [20260901, 20260902, 20260903]


def test_closed_loop_consistency_zero_residual():
    """Series are generated by the floor λ; the fit recovers it exactly."""
    r = calibrate_params(seeds=SEEDS)
    assert r.samples > 0 and r.decay_gaps == len(SEEDS) * len(KERNEL_STATES)
    for key in KERNEL_STATES:
        assert r.residuals[key] < 1e-6  # exact inversion of the pure form
        assert r.calibrated[key] == r.floors[key]  # == floor (== fitted, rounded)
        # fitted λ matches the generating floor
        assert abs(r.fitted[key] - DECAY_PARAMS[key][1]) < 1e-6


def test_tagged_series_separation():
    series = simulate_decay_series(state_key="energy", seed=SEEDS[0], days=2)
    tags = [t for _, _, t in series]
    # decay/delta alternate (delta steps push the state, decay steps idle)
    assert DECAY_TAG in tags and DELTA_TAG in tags
    # every decay step moves TOWARD the baseline relative to its predecessor
    b = DECAY_PARAMS["energy"][0]
    for (t0, x0, _), (t1, x1, tag1) in zip(series, series[1:]):
        if tag1 == DECAY_TAG and t1 - t0 > 1.0:  # idle gap
            assert abs(x1 - b) <= abs(x0 - b) + 1e-12


def test_fit_lambda_on_synthetic_perfect_series():
    """A pure-decay series (no deltas) fits λ exactly, whatever its value."""
    true_lambda = 0.03
    b = 0.5
    x = 0.9
    series = [(0.0, x, DECAY_TAG)]
    t = 0.0
    for gap in (3.0, 5.0, 8.0):
        t_next = t + gap
        x_next = b + (x - b) * math_exp(-true_lambda * gap)
        series.append((t_next, x_next, DECAY_TAG))
        t, x = t_next, x_next
    # temporarily point DECAY_PARAMS at a neutral baseline for the fit
    import lifeos.kernel.calibrate as cal

    original = dict(cal.DECAY_PARAMS)
    cal.DECAY_PARAMS["energy"] = (b, 0.02)  # baseline matters; lambda floor ignored by fit
    try:
        fitted = fit_lambda(series, state_key="energy")
        assert abs(fitted - true_lambda) < 1e-9
    finally:
        cal.DECAY_PARAMS.clear()
        cal.DECAY_PARAMS.update(original)


def math_exp(x: float) -> float:
    import math

    return math.exp(x)


def test_fallback_keeps_floor_on_unusable_series():
    """A series with no decay signal => floor kept, residual recorded."""
    import lifeos.kernel.calibrate as cal

    # craft a "flat" series: x stays away from baseline, no decaying gaps
    flat = [(0.0, 0.9, DECAY_TAG), (5.0, 0.9, DECAY_TAG)]
    with pytest.raises(ValueError):
        fit_lambda(flat, state_key="energy")  # no decaying gaps -> fail-closed
    # calibrate_params keeps the floor when the fit is inconsistent (>50%)
    original = dict(cal.DECAY_PARAMS)
    cal.DECAY_PARAMS["energy"] = (0.5, 0.02)
    try:
        # monkeypatch simulate to return an inconsistent series
        def _flat_series(*, state_key, seed, days=7, events_per_day=3, delta_scale=0.1):
            return [(0.0, 0.5, DECAY_TAG), (2.0, 0.5, DECAY_TAG)]  # at baseline: no signal

        sim_backup = cal.simulate_decay_series
        cal.simulate_decay_series = _flat_series
        try:
            r = calibrate_params(seeds=[1], states=["energy"])
            assert r.calibrated["energy"] == 0.02  # floor kept
        finally:
            cal.simulate_decay_series = sim_backup
    finally:
        cal.DECAY_PARAMS.clear()
        cal.DECAY_PARAMS.update(original)


def test_real_series_interface():
    """The fit path accepts externally supplied tagged measurements."""
    # real-world shape: observations with timestamps and tags from a cohort
    real = [
        (0.0, 0.8, DECAY_TAG),
        (6.0, 0.8 * 0.5 + 0.5 * 0.5, DECAY_TAG),  # x(t)=b+(x0-b)e^{-λΔt}, λ=0.1, Δt=6
        (6.1, 0.55, DELTA_TAG),
        (12.0, 0.5 + (0.55 - 0.5) * 0.5, DECAY_TAG),  # λ=0.1, Δt≈5.9
    ]
    import lifeos.kernel.calibrate as cal

    original = dict(cal.DECAY_PARAMS)
    cal.DECAY_PARAMS["energy"] = (0.5, 0.02)
    try:
        fitted = fit_lambda(real, state_key="energy")
        assert 0.09 < fitted < 0.12  # recovers the true λ≈0.1 within tolerance
    finally:
        cal.DECAY_PARAMS.clear()
        cal.DECAY_PARAMS.update(original)


def test_determinism():
    r1 = calibrate_params(seeds=SEEDS)
    r2 = calibrate_params(seeds=SEEDS)
    assert r1.to_dict() == r2.to_dict()


def test_pure_decay_untouched():
    """Calibration never changes the decay function's semantics in-place."""
    # DECAY_PARAMS still carries the floor values after all calibration runs
    assert DECAY_PARAMS["energy"] == (0.5, 0.02)
    # pure function invariant: same (t0, x0, t) => same x(t)
    v1 = decay_value("energy", 0.9, t0=0.0, t=4.0)
    v2 = decay_value("energy", 0.9, t0=0.0, t=4.0)
    assert v1 == v2
