"""Kernel v1 parameter calibration (roadmap §1.2 calibration path).

The decay constants in ``DECAY_PARAMS`` are engineering floors (source (b)).
This module closes the calibration loop with SIMULATED observation data:

1. ``simulate_decay_series``: drive the pure decay function over a synthetic
   interaction series (deltas + idle gaps, all seeded) - the "measured"
   series a real dogfood cohort would produce. Every observation is TAGGED
   ``decay`` (idle gap, state moved toward baseline) or ``delta``
   (interaction push, no decay signal) - the calibration version of the
   monitor/judge sampling separation;
2. ``fit_lambda``: invert the closed form x(t) = b + (x0-b)*exp(-λΔt) per
   DECAY-tagged gap (exact invertibility of the pure function makes this a
   consistency check, not statistical regression);
3. ``calibrate_params``: floor + fitted => calibrated table with the floor
   KEPT as fallback and residuals recorded (new ADR per roadmap §1.2, never
   in-place edits of DECAY_PARAMS semantics).

Honest scope: the "measurement" here is synthetic (continuity-sim series).
Real calibration binds when dogfood data exists - the interface (tagged
series in, params out) does not change.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Any

from lifeos.kernel.decay import DECAY_PARAMS, KERNEL_STATES, decay_value

# Observation tags: only DECAY gaps carry a lambda signal.
DECAY_TAG = "decay"
DELTA_TAG = "delta"


@dataclass
class CalibrationReport:
    """Deterministic calibration result per state key."""

    fitted: dict[str, float] = field(default_factory=dict)
    floors: dict[str, float] = field(default_factory=dict)
    calibrated: dict[str, float] = field(default_factory=dict)
    residuals: dict[str, float] = field(default_factory=dict)  # |fitted - floor| per state
    decay_gaps: int = 0
    samples: int = 0
    seed: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "fitted": self.fitted,
            "floors": self.floors,
            "calibrated": self.calibrated,
            "max_residuals": self.residuals,
            "decay_gaps": self.decay_gaps,
            "samples": self.samples,
            "seed": self.seed,
        }


def simulate_decay_series(
    *,
    state_key: str,
    seed: int,
    days: int = 7,
    events_per_day: int = 3,
    delta_scale: float = 0.1,
) -> list[tuple[float, float, str]]:
    """Synthetic tagged series: [(t_hours, x_observed, tag), ...] over `days`.

    Deterministic (seeded rng): interaction deltas push the state (``delta``
    tag), idle gaps let it decay via the CURRENT floor params (``decay``
    tag). The decay steps are generated by the floor λ, so fitting the
    decay-tagged gaps recovers the generating λ (consistency loop); the same
    interface accepts real tagged measurements later.
    """
    b, _ = DECAY_PARAMS[state_key]
    rng = random.Random(seed)
    x = b
    series: list[tuple[float, float, str]] = [(0.0, x, DECAY_TAG)]
    for _ in range(days * events_per_day):
        # 1) idle gap: pure decay toward baseline (the measurable effect)
        gap = rng.uniform(2.0, 10.0)
        t_prev, x_prev, _ = series[-1]
        t = t_prev + gap
        x = decay_value(state_key, x_prev, t0=t_prev, t=t)
        series.append((t, x, DECAY_TAG))
        # 2) interaction delta: pushes away from / across the baseline (no signal)
        delta = rng.uniform(0.02, delta_scale) * (1 if rng.random() > 0.4 else -1)
        x = min(1.0, max(0.0, x + delta))
        series.append((t + 0.1, x, DELTA_TAG))
    return series


def fit_lambda(
    series: list[tuple[float, float, str]],
    *,
    state_key: str,
) -> float:
    """Recover λ from pure DECAY→DECAY gaps only (delta steps excluded).

    The series alternates decay/delta steps; a (decay, delta) pair is an
    interaction push (no decay signal), a (delta, decay) or (decay, decay)
    pair spans a pure idle gap where the state moved toward the baseline -
    those carry the λ signal (the calibration version of the monitor/judge
    sampling separation).

    Per usable gap: λ_i = ln(|x0-b| / |x1-b|) / Δt; the estimate is the
    gap-length-weighted mean (exact for the pure form when the series was
    generated by the same λ - residuals ≈ 0).
    """
    b, _ = DECAY_PARAMS[state_key]
    num = 0.0
    den = 0.0
    for (t0, x0, tag0), (t1, x1, tag1) in zip(series, series[1:]):
        if tag1 != DECAY_TAG:  # the gap must END on a decay observation
            continue  # (t0, delta-t1) pairs are interaction pushes
        dt = t1 - t0
        if dt <= 0:
            continue
        d0 = abs(x0 - b)
        d1 = abs(x1 - b)
        if d0 < 1e-12 or d1 < 1e-12:
            continue  # at/near baseline: no signal
        if d1 >= d0:
            continue  # not toward baseline: no decay signal in this gap
        num += (math.log(d0 / d1) / dt) * dt
        den += dt
    if den == 0:
        raise ValueError(f"no decaying gaps in series for {state_key!r}")
    return num / den


def calibrate_params(
    *,
    seeds: list[int],
    states: list[str] | None = None,
    days: int = 7,
) -> CalibrationReport:
    """Fit λ per state from simulated series; floors kept as fallback.

    ``calibrated`` = fitted when the fit is consistent with the floor
    (residual < 50% of floor - synthetic series are generated by the floor,
    so a large residual means the series is unusable, not that the floor is
    wrong); otherwise the floor is kept and the residual recorded.
    """
    states = states or list(KERNEL_STATES)
    report = CalibrationReport(seed=seeds[0] if seeds else 0)
    all_samples = 0
    decay_gaps = 0
    for key in states:
        lam_samples = []
        for seed in seeds:
            series = simulate_decay_series(state_key=key, seed=seed, days=days)
            all_samples += len(series)
            try:
                lam_samples.append(fit_lambda(series, state_key=key))
            except ValueError:
                continue  # unusable series (no decay signal): this seed skipped
        floor = DECAY_PARAMS[key][1]
        if not lam_samples:
            # no usable series at all: keep the floor (fail-safe, not fail-open)
            report.fitted[key] = floor
            report.floors[key] = floor
            report.calibrated[key] = floor
            report.residuals[key] = 0.0
            continue
        fitted = sum(lam_samples) / len(lam_samples)
        residual = abs(fitted - floor)
        report.fitted[key] = round(fitted, 6)
        report.floors[key] = floor
        # consistency: synthetic series carry the floor's λ (exact inversion);
        # accept the fit only when it stays within 50% of the floor
        if residual <= 0.5 * floor:
            report.calibrated[key] = round(fitted, 6)
        else:
            report.calibrated[key] = floor  # fallback: keep the floor
        report.residuals[key] = round(residual, 6)
        decay_gaps += len(lam_samples)
    report.samples = all_samples
    report.decay_gaps = decay_gaps
    return report
